sudo: false

language: php

php:
  - 7

matrix:
    include:
        - php: 7
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - phpunit --coverage-text

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
